openapi: '3.0.2'
info:
  title: IMB Product Store API
  version: '1.0'
  description: API for connecting to the Information Management Branch Product store. It allows devs to surface a current product list, 
              along with relevant info, as well as devs and scrum masters working on products. Done for BC IMB code challange.
  contact:
    name: Alex Schell     
    email: alexschell@protonmail.com         
servers:
  - url: http://localhost:3000/api
    description: Dev server
paths:
  /product/{ProductID}:
  
    
    delete:
      description: Given the ID of a product, removes it from the database.
      parameters:
        - name: ProductID
          in: path
          required: True
          description: The hexadecimal Product ID of the product to remove.
          content:
            application/json:
              schema:
                type: string
                format: hex
      responses:
          '200':
            description: The product in the database was deleted sucessfully.
  /employee:
    get:
      description: Get a list of all employees that have been assigned as scrum master or developer on a product.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  employees: 
                    type: array
                    items: 
                      type: string
                      example: Dev a

  /employee/{employee name}/developed:
    get:
      description: Get a list of all products an employee worked on as a developer.
      parameters:
        - name: employee
          in: path
          required: True
          description: The name of the employee to search for, with spaces replaced with underscores (_)
          content:
            application/json:
              schema:
                type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  products: 
                    type: array
                    items: 
                      type: string
                      format: hexadecimal
                      example: cd21eacb687ce637f8592a49a238abfe086de6db
  /employee/{employee name}/scrummed:
    get:
      description: Get a list of all products an employee worked on as a scrum master.
      parameters:
        - name: employee
          in: path
          required: True
          description: The name of the employee to search for, with spaces replaced with underscores (_)
          content:
            application/json:
              schema:
                type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  products: 
                    type: array
                    items: 
                      type: string
                      format: hexadecimal
                      example: cd21eacb687ce637f8592a49a238abfe086de6db
